runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /(.*)
  static_files: build/(.*)
  upload: build/(.*)
- url: /static/(.*)
  static_files: build/static/(.*)
  upload: build/static/(.*)

