

export default {
    LAYERS: 0,
    AUDIO: 1,
    PROJECTSETTINGS: 2,
    ADDRESOURCEOPTIONS: 3,
    ADDLAYEROPTIONS: 4,
    ITEM: 5,
    AUDIOREACTIVETYPELIST: 6,
    LAYER: 7,
    ITEMS: 8,
    EFFECT: 9,
    NEWEFFECT: 10,
    ADDRESOURCEOPTIONS2D: 11,
}
